# Python review

Short review about some core concepts in Python exemplefied by objects in the Numpy library.
Goals:
- recall basic Python vocabulary
- practice markdown syntax

## Libraries and packages

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files. 

**NumPy:**

- core library for numerical computing in Python
- many of libraries use NumPy arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage

Let's import NumPy with its **standard abbreviation** `np`:

In [2]:
import numpy as np

(esc + press M twice -> convert code cell to markdown cell)
## Variables 

**variable:** a name we assign to a particular object in Python

Example:

In [3]:
# Assign a small array to a variable a 
a = np.array([ [1,1,2], [3,5,8] ])

To view a variable's value from our Jupyter notebook:

In [4]:
# Run a cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

An **object** is a bundle of properties and actions about something specific


## Types

Every object in Python has a **type**. The type tells us what kind of object it is. Also known as **class**

In [6]:
# Use the `type` function to see the type/class of a variable/object
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [9]:
# Check the type on an entry in the array by indexing
print(a[0,0])
type(a[0,0])

1


numpy.int64

Notice that 1 is stored as a 64-bit integer. NumPy has its own data types to deal with numbers depending on memory storage and floating point precision

In [14]:
# CHECK IN! access the value 5 in the array `a`
print(a[1,1])

5


## Functions

**Functions** take in a set of *arguments*, separated by commas, and use those arguments to create an *output*

Several built-in functions, most of them are for interacting with the Python basic data types such as:
- `int` (integers)
- `float` (decimal numbers)
- `str` (strings)
- `bool` (boolean values)

A **parameter** is a variable in the function definition that accepts an argument passed to the function. It is a placeholder in the function that will receive the value of an argument when the function is called. 
For example, in the function

In [15]:
def my_function(parameter1, parameter2):
    return parameter1+parameter2

`parameter1` and `parameter2` are parameters. When we call the function

In [16]:
result = my_function(5, 10)

we have that `5` and `10` are arguments passed to the function `my_function`

In [17]:
# Ask for information about what a function does by exectuting `?` followed by function name
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


## Attributes & methods 

An **attribute** is a propety of the object, some piece of information about it
A **method** is a procedure associated with an object, or a function that acts on the object it is a part of

In [19]:
# A 3x3 array
var = np.array([[1,2,3],[4,5,6],[7,8,9]])
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`T` is an example of attribute, it returns the transpose of `var`

In [20]:
print(var.T)
print(type(var.T))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
<class 'numpy.ndarray'>


In [21]:
# `shape`, another attribute, tells us the shape of the array:
print(var.shape)
print(type(var.shape))

(3, 3)
<class 'tuple'>


In [22]:
# `ndim` is an attribute holding the number of array dimensions
print(var.ndim)
print(type(var.ndim))

2
<class 'int'>


In [23]:
# The `.tolist()` method returns the array as a nested list of scalars:
var.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
# in `min` method returns the minimum value in the array along a specified axis:
var.min(axis = 0)

array([1, 2, 3])

In [27]:
type(var.tolist)

builtin_function_or_method

In [28]:
type(var.min)

builtin_function_or_method